version: '3'

services:
  web:
      image: nginx:latest
      ports:
          - "8080:80"
      volumes:
          - /Users/arlyxiao/dev/some-crm:/code
          - /Users/arlyxiao/dev/docker-configs/php-dev/site.conf:/etc/nginx/conf.d/default.conf
      links:
          - php
  php:
      build:
        context: ./php
        dockerfile: Dockerfile
      volumes:
          - /Users/arlyxiao/dev/some-crm:/code
